repos:
-   repo: local
    hooks:
    -   id: ruff
        name: ruff
        entry: make lint-auto-fix
        language: system
        types: [python]
        pass_filenames: false
    -   id: ruff-format
        name: ruff-format
        entry: make format
        language: system
        types: [python]
        pass_filenames: false
    -   id: mypy
        name: mypy
        entry: make type-check
        language: system
        types: [python]
        pass_filenames: false
